import React, { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { fetchReports } from "@/lib/engageApi";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { getAgentMeta, hexAlpha, timeAgo } from "@/lib/agentMeta";
import { useConversationStore } from "@/store/uiStore";
import { FileText } from "lucide-react";

function ReportSheet({ report, onClose }) {
  if (!report) return null;
  const meta = getAgentMeta(report.agent_id);
  return (
    <Sheet open={!!report} onOpenChange={(o) => !o && onClose()}>
      <SheetContent
        side="right"
        className="w-full sm:max-w-lg overflow-y-auto"
        data-testid="report-sheet"
      >
        <SheetHeader>
          <SheetTitle>{report.title}</SheetTitle>
        </SheetHeader>
        <div className="mt-2 flex items-center gap-2 text-xs text-text-secondary">
          <div
            className="w-5 h-5 rounded-full flex items-center justify-center text-white text-[9px] font-semibold"
            style={{ backgroundColor: meta.color }}
          >
            {meta.name[0]}
          </div>
          <span>
            Generated by {meta.name} · {timeAgo(report.last_generated_at)}
          </span>
        </div>

        <div className="mt-5">
          <h3 className="text-sm font-semibold text-text-primary uppercase tracking-wide">
            Findings
          </h3>
          <ul className="mt-2 space-y-2 text-sm text-text-secondary list-disc list-inside">
            {report.findings?.map((f, i) => (
              <li key={i}>{f}</li>
            ))}
          </ul>
        </div>

        <div className="mt-5">
          <h3 className="text-sm font-semibold text-text-primary uppercase tracking-wide">
            Recommended actions
          </h3>
          <ul className="mt-2 space-y-2 text-sm text-text-secondary list-decimal list-inside">
            {report.actions?.map((a, i) => (
              <li key={i}>{a}</li>
            ))}
          </ul>
        </div>
      </SheetContent>
    </Sheet>
  );
}

export default function ScheduledReports() {
  const [openReport, setOpenReport] = useState(null);
  const openWith = useConversationStore((s) => s.openWith);

  const { data: reports = [] } = useQuery({
    queryKey: ["reports"],
    queryFn: fetchReports,
    staleTime: 5 * 60_000,
  });

  const discuss = (r) => {
    openWith({
      seedMessage: `Walk me through this week's ${r.title.toLowerCase()}.`,
      pinnedAgent: r.agent_id,
      source: "report",
    });
  };

  return (
    <section data-testid="scheduled-reports">
      <div className="flex items-center justify-between mb-3">
        <h2 className="text-base font-semibold text-text-primary">
          Scheduled reports
        </h2>
        <button
          type="button"
          className="text-xs text-text-muted hover:text-text-secondary"
          data-testid="report-settings-link"
          title="Coming soon"
        >
          Report settings
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {reports.map((r) => {
          const meta = getAgentMeta(r.agent_id);
          return (
            <div
              key={r.id}
              data-testid={`report-card-${r.id}`}
              className="bg-surface border border-border rounded-lg p-4 flex flex-col"
            >
              <div className="flex items-start gap-2 mb-2">
                <FileText className="w-4 h-4 text-text-muted mt-1" />
                <div className="flex-1">
                  <h3 className="text-[15px] font-semibold text-text-primary">
                    {r.title}
                  </h3>
                  <div className="mt-1 inline-flex items-center gap-1.5 text-[11px]">
                    <div
                      className="w-4 h-4 rounded-full flex items-center justify-center text-white text-[8px] font-semibold"
                      style={{ backgroundColor: meta.color }}
                    >
                      {meta.name[0]}
                    </div>
                    <span className="text-text-secondary">
                      {meta.name} · {r.cadence}
                    </span>
                  </div>
                </div>
              </div>

              <ul className="mt-2 space-y-1 text-[12px] text-text-secondary list-disc list-inside line-clamp-3">
                {(r.findings || []).slice(0, 3).map((f, i) => (
                  <li key={`${r.id}-finding-${i}`} className="truncate">
                    {f}
                  </li>
                ))}
              </ul>

              <div
                className="mt-3 inline-block self-start px-2 py-0.5 rounded-full text-[10px] font-medium"
                style={{ backgroundColor: hexAlpha(meta.color, 0.12), color: meta.color }}
              >
                {r.action_count} recommended actions
              </div>

              <div className="mt-auto pt-4 flex items-center gap-2">
                <button
                  type="button"
                  data-testid={`report-read-${r.id}`}
                  onClick={() => setOpenReport(r)}
                  className="px-3 py-1.5 text-[12px] font-medium rounded-md bg-primary text-white hover:bg-primary-hover"
                >
                  Read report
                </button>
                <button
                  type="button"
                  data-testid={`report-discuss-${r.id}`}
                  onClick={() => discuss(r)}
                  className="px-3 py-1.5 text-[12px] rounded-md border border-border text-text-secondary hover:bg-slate-50"
                >
                  Discuss with {meta.name}
                </button>
              </div>
            </div>
          );
        })}
      </div>

      <ReportSheet report={openReport} onClose={() => setOpenReport(null)} />
    </section>
  );
}
